// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cxaqmzlgmsixhdzlfnuq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN4YXFtemxnbXNpeGhkemxmbnVxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExMjA3NDYsImV4cCI6MjA2NjY5Njc0Nn0.i4N1ZT0tzXWAo_IyC-48sNtCV9hsSxlog1botp-i01k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);